name: NEW Environment Approval Workflow


on:
  push:
    branches:
      - main

jobs:
   
  deploy:
    name: Deploy to Environments
    runs-on: ubuntu-latest
    needs: auto_approve
    outputs:
      mymatrix: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [item1, item2]

    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add steps to build and package your application

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          echo "I run post approval for ${{ matrix.environment }}"

  auto_approve:
    #needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Deploys
        # you can use any @vN.N.N tag from https://github.com/activescott/automate-environment-deployment-approval/releases
        uses: activescott/automate-environment-deployment-approval@main
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_AUTO_APPROVING_DEPLOYS }}
          environment_allow_list: |
            item1
            item2
          # The below automatically approves dependabot and anything submitted by the Github user with login "activescott"
          actor_allow_list: |
            dependabot[bot]          
            mohtashims    

  # upload:
  #   needs: [deploy, auto_approve]
  #   runs-on: ubuntu-latest
  #   environment: ${{ matrix.environment }}
  #   strategy:
  #     matrix:
  #       environment: ${{ fromJson(needs.deploy.outputs.mymatrix) }}
  #   steps:
  #     - run: echo '${{ matrix.environment }}'            
