name: Redirect Inputs to File

on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1'
        required: true
        default: 'Default Value 1'
      input2:
        description: 'Input 2'
        required: true
        default: 'Default Value 2'
      input3:
        description: 'Input 3'
        required: true
        default: 'Default Value 3'

jobs:
  redirect-inputs:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script to dump inputs to file
        shell: pwsh
        run: |
          # Convert inputs to PowerShell hashtable
          $Inputs = ${{ toJson(github.event.inputs) }}  | ConvertFrom-Json
          #$Inputs = $env:INPUTS_JSON | ConvertFrom-Json
    
          # Convert hashtable to JSON
          $InputData = $Inputs | ConvertTo-Json
    
          # Redirect inputs to a file
          $InputData | Out-File -FilePath inputs.json
    
          # Display the content of the file for verification
          Get-Content -Path inputs.json

      - name: Run PowerShell script to read inputs from file
        shell: pwsh
        run: |
          # Read inputs from inputs.json file
          $InputData = Get-Content -Path inputs.json | ConvertFrom-Json

          # Assign variables from input data
          $Input1 = $InputData.input1
          $Input2 = $InputData.input2
          $Input3 = $InputData.input3

          # Display the values of variables for verification
          Write-Output "Input1: $Input1"
          Write-Output "Input2: $Input2"
          Write-Output "Input3: $Input3"


      - name: Run PowerShell script
        shell: Powershell
        run: |
          # Convert inputs to JSON
          #$InputData = ConvertTo-Json -InputObject ${{ toJson(github.event.inputs) }}
          # Convert inputs to JSON and store in $InputData variable
          $InputData = ${{ toJson(github.event.inputs) }}

          # Redirect inputs to a file
          $InputData | Out-File -FilePath /tmp/inputs.json

          # Display the content of the file for verification
          Get-Content -Path /tmp/inputs.json

        
