name: Colorful Workflow

on:
  push:
    branches:
      - main

jobs:
  colorful_job_linux:
    name: Colorful Job NONWIN
    runs-on: ubuntu-latest

    steps:
      - name: Print colored text
        run: |
          echo -e "\e[32mThis is green text\e[0m"
          echo -e "\e[31mThis is red text\e[0m"


  colorful_job_win:
    name: Colorful Job WIN
    runs-on: windows-latest

    steps:
      - name: Print colored text
        shell: pwsh
        run: |

          Write-Host "`e[32mGreen Text`e[0m" -NoNewline
          Write-Host "`e[33mYellow Text`e[0m" -NoNewline
          Write-Host "`e[34mBlue Text`e[0m" -NoNewline
          Write-Host "`e[35mMagenta Text`e[0m" -NoNewline
          Write-Host "`e[36mCyan Text`e[0m" -NoNewline
          Write-Host "`e[31mRed Text`e[0m"
        
          #Write-Host "This is $(Write-Host "green text" -ForegroundColor Green)"
          #Write-Host "This is $(Write-Host "red text" -ForegroundColor Red)"    
