name: description for environment
on:
 push:
   branches:
     - main
jobs:
 Approvals:
   name: ${{ matrix.envName }}
   description: Job for approvals in different environments xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   
   runs-on: Windows-latest
   strategy:
     matrix:
       envName:
         - APP_APPROVAL
         - DB_APPROVAL
   environment:
     name: ${{ matrix.envName }}
   steps:
     - name: Extract Environment from SERVER_ENVIRONMENT
       id: getenv
       run: |
         Write-Host "Run Success"
