name: Loop Over Comma-Separated Values

on:
  push:
    branches:
      - main

jobs:
  createloopmatrix:
    runs-on: windows-latest

    steps:
      - name: Run PowerShell script
        shell: pwsh
        run: |

          $EnvNamesJSONVariable = @{}
          $envList = New-Object System.Collections.ArrayList
          $displayList = New-Object System.Collections.ArrayList
          
          $color = "hello, yellow"
          $values = $color.Split(',')

          $matrix = @()
          foreach ($value in $values) {
            $matrixname = "MA_$value"
            $envList.Add($value)
            $displayList.Add($matrixname)
            Write-Output "Value: $value"
          }


          $outputData = @{
            "DISPLAYLIST" = $displayList
            "CUSTOMENVNAME" = $envList
          }

          echo "ENV-MATRIX=$($outputData | ConvertTo-Json -Compress -Depth 100)" >> "$env:GITHUB_OUTPUT"
          

  Trigger_Service:
    name: ${{ matrix.DISPLAYLIST }}
    needs: [createloopmatrix]
    runs-on: windows-latest
    strategy:
      matrix:
        DISPLAYLIST: ${{ needs.createloopmatrix.outputs.DISPLAYLIST }}
        CUSTOMENVNAME: ${{ needs.createloopmatrix.outputs.CUSTOMENVNAME }}
    steps:
      - name: Split Matrix name for use
        run: |
          Write-Host "Inside Matrix"
