name: Loop Over Comma-Separated Values

on:
  push:
    branches:
      - main

jobs:
  createloopmatrix:
    runs-on: windows-latest

    steps:
      - name: Run PowerShell script
        shell: pwsh
        run: |

          $EnvNamesJSONVariable = @{}
          $envList = New-Object System.Collections.ArrayList
          $displayList = New-Object System.Collections.ArrayList
          
          $color = "hello, yellow"
          $values = $color.Split(',')

          foreach ($value in $values) {
            $matrixname = "MA" + "_" + "$value"
            $envList.Add($value)
            $displayList.Add($matrixname)
            Write-Output "Value: $value"
          }

          #$EnvNamesJSONVariable.Add("DISPLAYLIST",$displayList)
          #$EnvNamesJSONVariable.Add("CUSTOMENVNAME",$envList)
          #Write-Host "Tracker@11 - EnvNamesJSONVariable is $EnvNamesJSONVariable and Compress is $($EnvNamesJSONVariable | ConvertTo-JSON -Compress -Depth 100)" 
          #echo "ENV-MATRIX=$($EnvNamesJSONVariable | ConvertTo-JSON -Compress -Depth 100)" >> "$env:GITHUB_OUTPUT"

          $outputData = @{
            "DISPLAYLIST" = $displayList
            "CUSTOMENVNAME" = $envList
          }

          echo "ENV-MATRIX=$($outputData | ConvertTo-Json -Compress -Depth 100)" >> "$env:GITHUB_OUTPUT"
          

  Trigger_Service:
    name: ${{ matrix.DISPLAYLIST }}
    needs: [createloopmatrix]
    runs-on: windows-latest
    strategy:
      matrix:
        DISPLAYLIST: ${{ needs.createloopmatrix.outputs.DISPLAYLIST }}
        CUSTOMENVNAME: ${{ needs.createloopmatrix.outputs.CUSTOMENVNAME }}
    steps:
      - name: Split Matrix name for use
        run: |
          Write-Host "Inside Matrix"

  # Trigger_Service:
  #   name: ${{ matrix.DISPLAYLIST }}
  #   needs: [createloopmatrix]
  #   environment: 
  #     name: ${{ matrix.CUSTOMENVNAME }}
  #   runs-on: windows-latest
  #   strategy:
  #     matrix: ${{fromJSON(needs.createloopmatrix.outputs.ENV-MATRIX)}}
      
  #   steps:

  #     - name: Split Matrix name for use 
  #       run: |
  #         Write-Host "Inside Matrix"        

  
