name: Loop Over Comma-Separated Values

on:
  push:
    branches:
      - main

jobs:
  createloopmatrix:
    runs-on: windows-latest

    steps:
      - name: Run PowerShell script
        shell: pwsh
        run: |

          $EnvNamesJSONVariable = @{}
          $envList = New-Object System.Collections.ArrayList
          $displayList = New-Object System.Collections.ArrayList
          
          $color = "hello, yellow"
          $values = $color.Split(',')

          $matrix = @()
          foreach ($value in $values) {
            $matrixName = "MA_$value"
            $matrix += @{ "DISPLAYLIST" = $matrixName; "CUSTOMENVNAME" = $value }
            Write-Output "Value: $value"
          }

          echo "MATRIX=$($matrix | ConvertTo-Json -Compress -Depth 100)" >> "$env:GITHUB_OUTPUT"
          

  Trigger_Service:
    name: ${{ matrix.DISPLAYLIST }}
    needs: [createloopmatrix]
    runs-on: windows-latest
    strategy:
      matrix: ${{ fromJson(needs.createloopmatrix.outputs.MATRIX) }}
    steps:
      - name: Split Matrix name for use
        run: |
          Write-Host "Inside Matrix"

  # Trigger_Service:
  #   name: ${{ matrix.DISPLAYLIST }}
  #   needs: [createloopmatrix]
  #   environment: 
  #     name: ${{ matrix.CUSTOMENVNAME }}
  #   runs-on: windows-latest
  #   strategy:
  #     matrix: ${{fromJSON(needs.createloopmatrix.outputs.ENV-MATRIX)}}
      
  #   steps:

  #     - name: Split Matrix name for use 
  #       run: |
  #         Write-Host "Inside Matrix"        

  
