name: Your_Workflow - AD

on:
  push:
    branches:
      - main

jobs:
  CONSTRUCT_UPLOAD_ZIP:
    outputs:
      NEWENV-MATRIX: ${{ steps.newmatrixtask.outputs.newgenmatrix }}

    runs-on: windows-latest

    steps:
      - name: Construct new zip per environment
        id: newmatrixtask
        run: |
          $unique_envList = "item1 item2 item3"  # Replace with your logic to get unique_envList
          $envArray = $unique_envList -split ' '
          $newmatrix = $envArray | ConvertTo-Json
          echo "newgenmatrix='$newmatrix'" >> $env:GITHUB_OUTPUT


  upload-to:
    needs: CONSTRUCT_UPLOAD_ZIP
    runs-on: windows-latest

    strategy:
      matrix:
        envName: ${{fromJson(needs.CONSTRUCT_UPLOAD_ZIP.outputs.NEWENV-MATRIX)}}

    env:
      envName: ${{ matrix.envName }}

    steps:
      - name: Upload to JFrog
        run: |
          echo "Uploading for the environment: ${{ matrix.envName }}"
