on: push
jobs:
  matrix:
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    runs-on: windows-latest
    steps:
      - id: gen-matrix
        run: |
          $envList = "item1_pom item2 item3_xml item4_txt" -split ' '
          $unique_envList = @()
          foreach ($i in $envList) {
            if ($i -like '*_*') {
              $unique_envList += ($i -split '_')[0]
            }
          }
          $matrix = ConvertTo-Json $unique_envList -Compress
          echo "matrix=$matrix" >> "$env:GITHUB_OUTPUT"

          
  upload:
    needs: matrix
    runs-on: windows-latest
    strategy:
      matrix:
        environment: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - run: echo '${{ matrix.environment }}'
