name: Environment Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Environments
    runs-on: windows-latest

    strategy:
      matrix:
        environment: [item1, item2]

    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and package your application

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          echo "I run post approval for ${{ matrix.environment }}"
