name: Environment Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Environments
    runs-on: windows-latest

    strategy:
      matrix:
        environment: [item1, item2]

    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build and package your application

      - name: Deploy to ${{ matrix.environment }} environment
        run: |
          # Add commands to deploy to the specified environment
        env:
          ENVIRONMENT: ${{ matrix.environment }}

      - name: Ask for approval
        if: matrix.environment == 'item1' || matrix.environment == 'item2'
        run: |
          echo "Please approve the deployment to ${{ matrix.environment }} environment."
          # You may send notifications or perform any other approval action here
