on: push
jobs:
  matrix:
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    runs-on: windows-latest
    steps:
      - id: gen-matrix
        run: |
          $envList = "item1_pom item2 item3_xml item4_txt" -split ' '
          $unique_envList = @()
          foreach ($i in $envList) {
            if ($i -like '*_*') {
              $unique_envList += ($i -split '_')[0]
            }
          }
          $matrix = ConvertTo-Json $unique_envList -Compress
          echo "matrix=$matrix" >> "$env:GITHUB_OUTPUT"


  auto_approve:
    needs: matrix
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Deploys
        # you can use any @vN.N.N tag from https://github.com/activescott/automate-environment-deployment-approval/releases
        uses: activescott/automate-environment-deployment-approval@v1.0.6
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_AUTO_APPROVING_DEPLOYS }}
          environment_allow_list: |
            item4
            item1
          # The below automatically approves dependabot and anything submitted by the Github user with login "activescott"
          actor_allow_list: |
            dependabot[bot]
            mohtashims

            
          
  upload:
    needs: [matrix, auto_approve]
    runs-on: windows-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - run: echo '${{ matrix.environment }}'

      # - name: Deploy
      #   run: |
      #     # Add commands to deploy to the specified environment
      #   env:
      #     ENVIRONMENT: ${{ matrix.environment }}      
