name: MATRIX AUTO APPROVAL

on: push
jobs:
  conmatrix:
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    runs-on: windows-latest
    strategy:
      matrix:
        item1: [item1]
        item2: [item2]
    steps:
      - id: gen-matrix
        run: echo "matrix=$matrix" >> "$env:GITHUB_OUTPUT"



  auto_approve:
    needs: conmatrix
    #runs-on: windows-latest
    runs-on: windows-latest
    steps:
         
          
      - name: Auto Approve Deploys
        # you can use any @vN.N.N tag from https://github.com/activescott/automate-environment-deployment-approval/releases
        uses: activescott/automate-environment-deployment-approval@v1.0.6
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_AUTO_APPROVING_DEPLOYS }}
          environment_allow_list: |
            item1
            item2

          # The below automatically approves dependabot and anything submitted by the Github user with login "activescott"
          actor_allow_list: |
            dependabot[bot]
            mohtashims

            
          
  upload:
    needs: [conmatrix, auto_approve]
    runs-on: windows-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ${{ fromJson(needs.conmatrix.outputs.matrix) }}
    steps:
      - run: echo '${{ matrix.environment }}'

      # - name: Deploy
      #   run: |
      #     # Add commands to deploy to the specified environment
      #   env:
      #     ENVIRONMENT: ${{ matrix.environment }}      
