name: MATRIX AUTO APPROVAL

on: push
jobs:

  auto_approve:
    #needs: conmatrix
    runs-on: windows-latest
    steps:
      - name: Auto Approve Deploys
        uses: activescott/automate-environment-deployment-approval@v1.0.6
        with:
          github_token: ${{ secrets.GH_TOKEN_FOR_AUTO_APPROVING_DEPLOYS }}
          environment_allow_list: |
            item1
            item2
          actor_allow_list: |
            dependabot[bot]
            mohtashims

  conmatrix:
    needs: auto_approve  
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    runs-on: windows-latest
    strategy:
      matrix:
        items:
          - item1
          - item2
    steps:
      - id: gen-matrix
        run: |
          $matrix = ConvertTo-Json $matrix -Compress
          echo "matrix=$matrix" >> "$env:GITHUB_OUTPUT"


            
          
  upload:
    needs: [conmatrix, auto_approve]
    runs-on: windows-latest
    steps:
      - name: Set Environment Matrix
        id: set_matrix
        run: echo "::set-output name=matrix::$(cat $env:GITHUB_OUTPUT)"
      
      - name: Display Matrix
        run: echo "${{ steps.set_matrix.outputs.matrix }}"
