name: execute-paralell

on:
  push:
    branches:
      - main

jobs:

  Trigger_Service:
    name: "${{ matrix.item }}"
    runs-on: "windows-latest"
    strategy:
      matrix:
        item: ["item1", "item2", "item3"]
    steps:
      - name: Step task which prints
        id: instancedetails
        run: |
          Start-Sleep -Seconds 15
          Write-Host "This is a test case for ${{ matrix.item }}"
